Algoritmo "semnome"

Var
// Seção de Declarações das variáveis 

   x,y: inteiro
   soma: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

        escreval("Digite o valor de X: ")
        leia(x)
        escreval("Digite o valor de Y: ")
        leia(y)
        soma <- x + y
        escreval("RESULTADO")
        escreval(soma)




Fimalgoritmo